name: Release
on:
  push:
    tags:
    - 'v*'
    - 'test-action-release-*'
env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    # The maximum access is "read" for PRs from public forked repos
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: write  # for releases
      id-token: write  # for provenances
      attestations: write  # for provenances
    steps:
    - uses: actions/setup-go@v6
      with:
        go-version: 1.24.x
    - uses: actions/checkout@v5
      with:
        path: go/src/github.com/containerd/fuse-overlayfs-snapshotter
    - name: "Compile binaries"
      working-directory:  go/src/github.com/containerd/fuse-overlayfs-snapshotter
      run: make artifacts
    - name: "SHA256SUMS"
      working-directory:  go/src/github.com/containerd/fuse-overlayfs-snapshotter
      run: |
        ( cd _output; sha256sum containerd-fuse-overlayfs-* ) | tee /tmp/SHA256SUMS
        mv /tmp/SHA256SUMS _output/SHA256SUMS
    - name: "The sha256sum of the SHA256SUMS file"
      working-directory:  go/src/github.com/containerd/fuse-overlayfs-snapshotter
      run: (cd _output; sha256sum SHA256SUMS)
    - name: "Prepare the release note"
      working-directory:  go/src/github.com/containerd/fuse-overlayfs-snapshotter
      run: |
        shasha=$(sha256sum _output/SHA256SUMS | awk '{print $1}')
        cat <<-EOF | tee /tmp/release-note.txt
        (To be documented)
        - - -
        The binaries were built automatically on GitHub Actions.
        The build log is available for 90 days: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        The sha256sum of the SHA256SUMS file itself is \`${shasha}\` .
        EOF
    - uses: actions/attest-build-provenance@v2
      with:
        subject-path: go/src/github.com/containerd/fuse-overlayfs-snapshotter/_output/*
    - name: "Create release"
      working-directory:  go/src/github.com/containerd/fuse-overlayfs-snapshotter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF##*/}"
        gh release create -F /tmp/release-note.txt --draft --title "${tag}" "${tag}" _output/*
